<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Sidecar</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sidecar\MeetingApp.Sidecar.csproj" />
    <ProjectReference Include="..\Nucleo\MeetingApp.Nucleo.csproj" />
  </ItemGroup>

</Project>
